url: "https://coderic.org"
baseurl: "/OmarYagua/"
title: "Coderic"
network: "TEAM"
name: "Omar Yagua Jr"
description: "Vice President"
avatar_img_path: "imgs/omar-yagua.jpg"
permalink: pretty
remote_theme: Coderic/coderic.org
